name: CI

on: [push]

jobs:
  test:
    name: Inspector
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: kamilkisiela/graphql-inspector@36111899d4e07cbe27251fad30a287aff0977184
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        schema: 'master:schema.graphql'
