name: CI

on: [push]

jobs:
  test:
    name: Inspector
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

#     - uses: kamilkisiela/graphql-inspector@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         schema: 'master:schema.graphql'
